<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Crm.ClientWebAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\**\*" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
